language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t seshudocker2020/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true seshudocker2020/docker-react npm run test
